using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.WPF.Reflection.Attributes;

namespace KSHairsBaldHelmetsFixer
{
    public static class MyExtensions
    {
        public static bool ContainsInsensitive(this string str, string rhs)
        {
            return str.Contains(rhs.Trim(), StringComparison.OrdinalIgnoreCase);
        }
    }

    public class Settings
    {

        public List<string[]> ParseIdFilters(IList<string> filterData)
        {
            List<string[]> result = new List<string[]>();
            foreach (var filterDataItem in filterData)
            {
                if (!String.IsNullOrEmpty(filterDataItem))
                {
                    string[] filterElements = filterDataItem.Split(',');
                    if (filterElements.Length > 0)
                    {
                        result.Add(filterElements);
                    }
                }
            }
            return result;
        }

        [MaintainOrder]

        private List<string[]> _blacklist = new List<string[]>();
        [SettingName("Blacklisted EditorIDs")]
        [Tooltip("Each entry is a comma separated list of partial EditorIDs, case insensitive.")]
        public List<string> Blacklist
        {
            get
            {
                List<string> idFilters = new List<string>();
                foreach (var filter in _blacklist)
                {
                    idFilters.Add(String.Join(",", filter));
                }
                return idFilters;
            }
            set
            {
                _blacklist = ParseIdFilters(value);
            }
        }
    }

    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        private static Lazy<Settings> _settings = null!;
        private static Settings Settings => _settings.Value;

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            string[] blacklist = { };// "kha", "arg" };
            blacklist = blacklist.Concat(string.Join(",", Settings.Blacklist).Split(",")).ToArray();
            foreach (var armorAddonGetter in state.LoadOrder.PriorityOrder.ArmorAddon().WinningContextOverrides())
            {
                var armorAddon = armorAddonGetter.Record;
                if (armorAddon.BodyTemplate == null ||
                    !armorAddon.BodyTemplate.FirstPersonFlags.HasFlag(BipedObjectFlag.LongHair) ||
                    armorAddon.EditorID == null || blacklist.Any(armorAddon.EditorID.ContainsInsensitive))
                {
                    continue;
                }
                var naa = state.PatchMod.ArmorAddons.GetOrAddAsOverride(armorAddon);
                Console.WriteLine($"Patching {naa.EditorID}");
                if (naa.BodyTemplate != null)
                {
                    naa.BodyTemplate.FirstPersonFlags &= ~BipedObjectFlag.LongHair;
                }
            }
        }
    }
}
